export const allBreakages = [
  { name: "OpenSSL Vulnerability", id: "CVE-2024-0567", severity: "Critical", color: "red" },
  { name: "Log4j Exposure", id: "CVE-2024-0891", severity: "High", color: "orange" },
  { name: "Node Package Issue", id: "npm-package-v3.2.1", severity: "High", color: "orange" },
  { name: "Outdated Python Module", id: "requests-2.26.0", severity: "Medium", color: "yellow" },
  { name: "Dependency Conflict", id: "zlib-1.2.11", severity: "Medium", color: "yellow" },
  { name: "Kubernetes RBAC Bypass", id: "CVE-2024-1234", severity: "Critical", color: "red" },
  { name: "PostgreSQL Injection", id: "postgresql-15.1", severity: "High", color: "orange" },
  { name: "Redis Memory Leak", id: "redis-7.0.5", severity: "Medium", color: "yellow" },
  { name: "Go HTTP/2 DoS", id: "CVE-2024-5678", severity: "High", color: "orange" },
  { name: "Java Deserialization", id: "CVE-2024-9999", severity: "Critical", color: "red" },  { name: "OpenSSL Vulnerability", id: "CVE-2024-0567", severity: "Critical", color: "red" },
  { name: "Log4j Exposure", id: "CVE-2024-0891", severity: "High", color: "orange" },
  { name: "Node Package Issue", id: "npm-package-v3.2.1", severity: "High", color: "orange" },
  { name: "Outdated Python Module", id: "requests-2.26.0", severity: "Medium", color: "yellow" },
  { name: "Dependency Conflict", id: "zlib-1.2.11", severity: "Medium", color: "yellow" },
  { name: "Kubernetes RBAC Bypass", id: "CVE-2024-1234", severity: "Critical", color: "red" },
  { name: "PostgreSQL Injection", id: "postgresql-15.1", severity: "High", color: "orange" },
  { name: "Redis Memory Leak", id: "redis-7.0.5", severity: "Medium", color: "yellow" },
  { name: "Go HTTP/2 DoS", id: "CVE-2024-5678", severity: "High", color: "orange" },
  { name: "Java Deserialization", id: "CVE-2024-9999", severity: "Critical", color: "red" },
  { name: "OpenSSL Vulnerability", id: "CVE-2024-0567", severity: "Critical", color: "red" },
  { name: "Log4j Exposure", id: "CVE-2024-0891", severity: "High", color: "orange" },
  { name: "Node Package Issue", id: "npm-package-v3.2.1", severity: "High", color: "orange" },
  { name: "Outdated Python Module", id: "requests-2.26.0", severity: "Medium", color: "yellow" },
  { name: "Dependency Conflict", id: "zlib-1.2.11", severity: "Medium", color: "yellow" },
  { name: "Kubernetes RBAC Bypass", id: "CVE-2024-1234", severity: "Critical", color: "red" },
  { name: "PostgreSQL Injection", id: "postgresql-15.1", severity: "High", color: "orange" },
  { name: "Redis Memory Leak", id: "redis-7.0.5", severity: "Medium", color: "yellow" },
  { name: "Go HTTP/2 DoS", id: "CVE-2024-5678", severity: "High", color: "orange" },
  { name: "Java Deserialization", id: "CVE-2024-9999", severity: "Critical", color: "red" },
];
